Update makecpt baseline images for GMT 6.2.0rc1
GenericMappingTools/pygmt pull request #1231
Opened 2021-04-22 21:05 UTC by meghanrjones

**Description of proposed changes**

Address #1217

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

2021-04-22 21:18 UTC, seisman approved these changes

2021-04-22 21:39 UTC, weiji14 approved these changes

2021-04-22 21:41 UTC, weiji14 requested changes
Actually, hold on, the `makecpt` tests are still failing https://github.com/GenericMappingTools/pygmt/pull/1231/checks?check_run_id=2414367157#step:11:687:

```
___________________________ test_makecpt_categorical ___________________________
Error: Image dimensions did not match.
  Expected shape: (122, 1432)
    /Users/runner/work/pygmt/pygmt/tmp-test-dir-with-unique-name/results/pygmt.tests.test_makecpt.test_makecpt_categorical/baseline.png
  Actual shape: (120, 1432)
    /Users/runner/work/pygmt/pygmt/tmp-test-dir-with-unique-name/results/pygmt.tests.test_makecpt.test_makecpt_categorical/result.png
_____________________________ test_makecpt_cyclic ______________________________
Error: Image dimensions did not match.
  Expected shape: (122, 1529)
    /Users/runner/work/pygmt/pygmt/tmp-test-dir-with-unique-name/results/pygmt.tests.test_makecpt.test_makecpt_cyclic/baseline.png
  Actual shape: (120, 1528)
    /Users/runner/work/pygmt/pygmt/tmp-test-dir-with-unique-name/results/pygmt.tests.test_makecpt.test_makecpt_cyclic/result.png
```

2021-04-22 23:18 UTC, meghanrjones commented
Locally it passes for me with `pytest pygmt/tests/test_makecpt.py` but fails with `make test`. I will need to look into this more but do not have time right now. I will tomorrow but if anyone else wants to take this over to finish quicker that is fine.

2021-04-27 03:20 UTC, weiji14 reviewed
Ad a URL to the PyGMT issue to keep track.

2021-04-27 03:20 UTC, weiji14 commented on pygmt/tests/test_makecpt.py
> +@pytest.mark.xfail(reason="Flaky test only passes with pytest on single module")
```suggestion
@pytest.mark.xfail(
    reason="Flaky test only passes with pytest on single module"
    "See https://github.com/GenericMappingTools/pygmt/issues/1242"
)
```

2021-04-27 03:20 UTC, weiji14 commented on pygmt/tests/test_makecpt.py
> +@pytest.mark.xfail(reason="Flaky test only passes with pytest on single module")
```suggestion
@pytest.mark.xfail(
    reason="Flaky test only passes with pytest on single module"
    "See https://github.com/GenericMappingTools/pygmt/issues/1242"
)
```

2021-04-27 03:24 UTC, weiji14 approved these changes

2021-04-27 04:11 UTC, merged