Add projection to grdview docstring
GenericMappingTools/pygmt pull request #1295
Opened 2021-05-25 23:20 UTC by meghanrjones

**Description of proposed changes**

The `projection` parameter is included in the list of aliases but not the docstring for grdview. This PR adds the projection description to the docstring.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

2021-05-25 23:28 UTC, weiji14 approved these changes

2021-05-25 23:30 UTC, weiji14 requested changes
Oh wait, actually, we're missing the region (R) docstring as well for this!

2021-05-25 23:30 UTC, weiji14 commented on pygmt/src/grdview.py
> +    {J}
```suggestion
    {R}
    {J}
```

2021-05-25 23:32 UTC, meghanrjones commented on pygmt/src/grdview.py
> +    {J}
Good catch, thanks

2021-05-25 23:48 UTC, weiji14 approved these changes
So region (-R) isn't actually a required argument for `grdview` according to https://docs.generic-mapping-tools.org/6.2.0rc2/grdview.html, but using `{R}` in the docstring here says that it is:

![image](https://user-images.githubusercontent.com/23487320/119582064-00645500-be18-11eb-9fd2-a74233c81334.png)

Wondering if we should edit the wording slightly at https://github.com/GenericMappingTools/pygmt/blob/01e2febb77f08370cb8ef8e23f7b1c42e9709c99/pygmt/helpers/decorators.py#L17-L21

Can open a separate issue/PR for this.

2021-05-25 23:53 UTC, meghanrjones commented
> 
> Wondering if we should edit the wording slightly
> 


I think the current wording is accurate for most plotting modules, so maybe I can just not use the replacement text for `grdview` but keep the wording from decorators.py as is to not affect other method docs?

2021-05-26 01:43 UTC, meghanrjones commented
Is the latest version OK with you, @weiji14?

2021-05-26 01:55 UTC, weiji14 commented
> Is the latest version OK with you, @weiji14?

Yep, looks good! I like that it explicitly specifies zmin/zmax too. Remember to change the PR title to include 'region' before merging.

2021-05-26 02:02 UTC, meghanrjones commented
Sounds good. One more question - when the checks fail for reasons clearly unrelated to the PR (like now), do you prefer for me to re-run all checks or admin merge the PR?

2021-05-26 02:08 UTC, weiji14 commented
> when the checks fail for reasons clearly unrelated to the PR (like now), do you prefer for me to re-run all checks or admin merge the PR?

I would just admin merge in this case to conserve CI resources.

2021-05-26 02:10 UTC, merged